# Put .pam_mount.conf.xml
---
- hosts: all
  vars:
     home_pam_mount_conf_xml: "{{ lookup('file', '.pam_mount.conf.xml') }}"
  tasks:
     - name: Install necessary packages
       copy: 
        content: "{{ home_pam_mount_conf_xml }}"
        dest: "{{ ansible_env.HOME }}/.pam_mount.conf.xml"
        mode: 0644
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
     - file:
        path: "{{ ansible_env.HOME }}/share"
        state: directory
        mode: 0755